In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('/content/drive/MyDrive/DL_data/DACON6/서울시 인구 이동/서울시 8월 생활이동데이터/생활이동_행정동_2022.08_09시.csv', encoding='cp949')

df.head()

     대상연월 요일  도착시간  출발 행정동 코드  도착 행정동 코드 성별  나이 이동유형  평균 이동 시간(분) 이동인구(합)
0  202208  일     9    1101053    1101053  F   0   HE           32   83.31
1  202208  일     9    1101053    1101053  F  10   WE            3    5.84
2  202208  일     9    1101053    1101053  F  15   HE           26    4.04
3  202208  일     9    1101053    1101053  F  15   WW           21    4.09
4  202208  일     9    1101053    1101053  F  15   HW           21    4.04